### ISSUE TITLE
add environment variable for reverse proxy base uri into servicemanifest.xml

### ISSUE THREAD

**Issue by jagilber** [Azure-Samples/service-fabric-dotnet-quickstart#10]
issue: unable to change protocol or port for reverseproxy without changing code
resolution: create ReverseProxyBaseUri environment variable in servicemanifest.xml 
modify service-fabric-quickstart-dotnet documentation
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-quickstart-dotnet

**Comment by jagilber** [comment]
submitted PR for documentation change 
https://github.com/MicrosoftDocs/azure-docs/pull/9375
discussed with @MikkelHegn

**Comment by MikkelHegn** [comment]
Approved and merged.
