### ISSUE TITLE
Latest SDK: Voting.sfproj: The application which this project type is based on was not found.

### ISSUE THREAD

**Issue by greigs** [Azure-Samples/service-fabric-dotnet-quickstart#4]
I am unable to load the Voting.sfproj using the latest version of VS2017 (15.5.2) with the latest version of the Microsoft Azure Service Fabric SDK (2.8.232).

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Voting, "C:\repo\service-fabric-dotnet-quickstart\Voting\Voting.sfproj"

**Comment by klettier** [comment]
Hello,

Your error seems not related to the version of the SDK you are using, are you sure to have selected **Service Fabric tools** during the VS 2017 installation.

![image](https://user-images.githubusercontent.com/3425823/35481380-c77caa60-0422-11e8-9c2a-facda915779f.png)

If it's not the case you can add it from **Microsoft visual studio Installer**

[Here](https://blogs.msdn.microsoft.com/azureservicefabric/2017/03/17/visual-studio-2017-and-service-fabric-tools/) is the detail of what should be installed

![image](https://user-images.githubusercontent.com/3425823/35481417-8901578a-0423-11e8-8fac-94d2dafa5f5b.png)

Hope it's help you

**Comment by hamstelfo** [comment]
Hi,

I'm getting some errors just after open the solution. I have to say that I already could run other Service Fabric examples like the Stateful Service example, and manage the local cluster, etc.. so I think I have all the necessary tools installed.

In this case, after just open the solution:
1) Got 15 erros like "The Microsoft.AspNetCore 2.0.1 package is not compatible with net461".. The same with Microsoft.AspNetCore.StaticFiles, Microsoft.Extensions.Logging.Debug, etc..
2) Also I got the notification of "NuGet packages should be restored".. Does not matter what I click,.. I got finally 46 erros like "The type or the namespace MVC does not exist in the namespace Microsoft.AspNetCore".

Could you help, please? Thanks.

**Comment by klettier** [comment]
Hello, 

Be sure to have **dotnet sdk** in at least version 2 installed and VS 2017 with last updates.

kevin

**Comment by MikkelHegn** [comment]
I'm closing this issue for now as it looks like the questions were resolved.

**Comment by SamHard** [comment]
I experienced a similar problem, and the VS installer had the "Service Fabric Tools" box checked already.  I was able to resolve the issue by unchecking that box, clicking "Update" so that the feature would be uninstalled, and then re-installing the feature.
